import { dirname, join, relative } from 'node:path';
import { locateTasks } from './utils.js';
import { readFile, writeFile } from 'node:fs/promises';

/**
 * SvelteKit Vite plugin for collecting Node tasks.
 * @param {{ suffix?: string }} [options] The plugin options.
 * @returns {import('vite').Plugin}
 */
export default function({ suffix } = {}) {
	return {
		name: 'sveltekit-node-tasks',

		async config(config, env) {
			const isBuild = env.command === 'build';
			const ssr = config.build?.ssr;
			if (!isBuild || !ssr) {
				return;
			}

			const tasks = locateTasks(suffix);
			const internalFile = join('.svelte-kit', 'generated', 'server', 'internal.js');

			// internal.js is generated by SvelteKit directly writing to the .svelte-kit folder
			// we need to append our tasks runner in order to include it in the build
			const contents = await readFile(internalFile, 'utf-8');
			await writeFile(
				internalFile,
				`${contents}\nexport async function run_task(task) {
const { filter_env } = await import('../../../node_modules/@sveltejs/kit/src/utils/env.js');

set_private_env(filter_env(process.env, options.env_private_prefix, options.env_public_prefix));
set_public_env(filter_env(process.env, options.env_public_prefix, options.env_private_prefix));

const tasks = {
	${tasks.map((task) => `'${task.name}': () => import('${relative(dirname(internalFile), task.path)}')`).join(',\n\t')}
};
if (!tasks[task]) {
	throw new Error('Task "' + task + '" not found');
}
return tasks[task]().then((mod) => {
	if (!mod.task) {
		throw new Error('Task "' + task + '" has no exported "task" function');
	}
	return mod.task();
});
}`
			);
		},

		async transform(code, id) {
			if (!id.endsWith('@sveltejs/kit/src/runtime/server/index.js')) {
				return;
			}

			// we need to export the run_task function from internal.js in order to preserve it
			// during the build, otherwise it gets tree-shaken away
			return `${code}\nexport { run_task } from '__SERVER__/internal.js'`;
		}
	};
}